root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/app ./cmd/server"
bin = "tmp/app"
full_bin = "APP_ENV=dev ./tmp/app"
include_ext = ["go", "tpl", "tmpl", "html", "yml", "yaml", "toml"]
exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
time = true
